name: federalnet_customer_app
description: Minimal Customer Flutter scaffold for FederalNet
version: 0.0.1
environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.0.0
  flutter_secure_storage: ^8.0.0

flutter:
  uses-material-design: true
