name: federalnet_admin_app
description: Minimal Admin Flutter scaffold for FederalNet
version: 0.0.1
environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.0.0
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.3.2

flutter:
  uses-material-design: true

dependency_overrides:
